restart-times: 3
jobscript: "slurm-jobscript.sh"
cluster-config: "cluster.yaml"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
max-jobs-per-second: 10
max-status-checks-per-second: 10
latency-wait: 80